server:
  profiles:
    include: private
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/review2
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: